name: Build Package

on:
  push:
    branches:
      - main  # Или ваша основная ветка

jobs:
  build:
    runs-on: ubuntu-latest  # Выберите ОС, подходящую для ваших нужд

    container:
      image: archlinux/base:latest

    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm base-devel

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build package
